on:
 push:
   branches:
      - main
      
 jobs:
   build:
     runs-on: windows-latest
       steps: Checkout
       uses: action/checkout@v3.3.0
       -run: docker build -t shaatra-api .
       -
